<?php
// Locale
$_['lc_monetary']           = 'en-US';
$_['code']                  = 'en';
$_['direction']             = 'ltr';
$_['date_format_short']     = 'd/m/Y';
$_['date_format_long']      = 'l dS F Y';
$_['time_format']           = 'h:i:s A';
$_['decimal_point']         = '.';
$_['thousand_point']        = ',';
$_['speed_unit']            = 'km/h';

// Text
$_['text_contact_section_description']    = '';
$_['text_contact_section_title']        = 'Contact Us';
$_['text_copyright']                    = '%s Copyright &copy; %s - All rights reserved. - Developed by: <a href="http://www.median.web.ve" target="_blank">mediaNweb</a>';
$_['text_event_name']                    = '';
$_['text_event_type_title']                = 'Branding';
$_['text_events_section_description']    = 'Here we have our most recent events.';
$_['text_events_section_title']            = 'Our Events';
$_['text_heading_title']                = 'Home';
$_['text_menu_title']                    = 'Menu';
$_['text_tag_line_1']                    = 'Accurate timing makes the game more exciting';
$_['text_tag_line_2']                    = 'And exactly that does RaceTimer';
$_['text_tag_line_word_1']                = 'practical';
$_['text_tag_line_word_2']                = 'reliable';
$_['text_tag_line_word_3']                = 'unique';
$_['text_result_instamagazine']            = 'Hi <strong>%s, </strong>Click the following link to see your instamagazine';
$_['text_result_instamagazine_link']    = 'Go there now';
$_['text_result_section_heading']        = 'Here are your results';
$_['text_result_col_athlete']            = 'You';
$_['text_result_col_overall']            = 'Overall Winner';
$_['text_result_col_gender']            = 'Gender Winner';
$_['text_result_col_bracket']            = 'Bracket Winner';
$_['text_result_cell_race_title']        = 'Race:';
$_['text_result_cell_bracket_title']    = 'Bracket:';
$_['text_result_cell_net']                = 'Net Time:';
$_['text_result_cell_gun']                = 'Gun Time:';
$_['text_result_cell_bracket']            = '<strong>%s</strong> of <strong>%s</strong> %s';
$_['text_result_cell_gender']            = '<strong>%s</strong> of <strong>%s</strong> %s';
$_['text_result_cell_overall']            = '<strong>%s</strong> of <strong>%s</strong> over-all';
$_['text_male']                            = 'Male';
$_['text_female']                        = 'Female';
$_['text_result_certificate']            = 'Do you need your race certificate?';
$_['text_result_certificate_link']        = 'Get it here';
$_['text_result_widget_link']            = 'Direct Result Widget';
$_['text_certificate_bib']                = 'Bib:';
$_['text_certificate_pace']                = 'Pace:';
$_['text_certificate_footer']            = 'Certificate generated by: https://virtualworldruns.com';
$_['text_certificate_overall']            = 'Overall Rank';
$_['text_certificate_gender']            = 'Gender Rank';
$_['text_certificate_bracket']            = 'Bracket Rank';
$_['text_certificate']                    = 'Certificate';
$_['text_participant']                    = 'Participant';

// Buttons
$_['button_close']                = 'Close';
$_['button_contact']            = 'Contact Us';
$_['button_dutch']                = 'Dutch';
$_['button_english']            = 'English';
$_['button_events']                = 'Our Events';
$_['button_french']                = 'French';
$_['button_get_in_touch']        = 'Get in Touch';
$_['button_go_to_events']        = 'Go To Events';
$_['button_home']                = 'Home';
$_['button_load_more_events']   = 'More Events';
$_['button_submit']                = 'Submit';
$_['button_swedish']            = 'Swedish';
$_['button_results']            = 'Get Results';

// Inputs
$_['input_contact_form_email_address']    = 'Email Address';
$_['input_contact_form_first_name']        = 'First Name';
$_['input_contact_form_last_name']        = 'Last Name';
$_['input_contact_form_message']        = 'Message';
$_['input_contact_form_subject']        = 'Subject';
$_['input_results_form_bib']            = 'Enter Your Bib';

// Error
$_['error_contact_form_message']    = 'There was a problem with your submission. Please check the field(s) with red label below.';
$_['error_contact_form_success']    = 'Your message has been sent. We\'ll get back to you soon!';
$_['error_no_data']                    = 'No athlete data found';
